# Your Name or Company
title: Анастасія Галич

# Description of your website. This is used for social sharing.
description:  Сайт доктора Анастасії Сергіївни Галич.

# A brief blurb about yourself
content: Всім привіт, я фельдшер Анастасія Галич. Консультую онлайн.

# Add your social links
social:
  - platform: telegram
    url: https://t.me/ANASTASIIA_GALICHY/
  - platform: facebook
    url: #
  - platform: tolza
    url: https://tolza.com.ua/
  - platform: linkedin
    url: #

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: half-sm.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
