# Your Name or Company
title: Анастасія Галич

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler.

# A brief blurb about yourself
content: Всім привіт, я лікар Анастасія Галич. Консультую онлайн.

# Add your social links
social:
  - platform: telegram
    url: https://t.me/ANASTASIIA_GALICHY/
  - platform: facebook
    url: https://facebook.com/#
  - platform: twitter
    url: https://twitter.com/#
  - platform: linkedin
    url: #

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
